[단테]  useGetData 혹으로 분리하기 , 나의 현재 위치 데이터 , 현재 위치와 가까운 화장실 위치 마커로 표현하기
wheres-my-toilet/wheres-my-toilet pull request #18
Opened 2024-03-21 07:51 UTC by Andante23

[MOD] types 폴더에 Location 정보 분리하기
[FEAT] home_page/page.tsx 부분에 현재 사용자에서 위치에서 가까운 화장실의 위치 마커로 나타내는 기능 구현

## Task TODOLIST

- [ ]  types 폴더에  Location 정보를 분리하였습니다.
- [ ]  geolocation으로부터 사용자의 위치와 가까운 화장실의 위치 마커로 나타내는 기능을 구현하였습니다.  

## ✨ 개발 내용

(1)  커스텀 혹으로 분리하면  이 로직을 다른 곳에서도 사용이 가능한 재사용이 용이하며 ,해당 로직에 대한 세부 사항을 알 필요가 없다는 것을 통해  컴포넌트의  추상화 및  역활이 명확해집니다. 그리하여 사용하였습니다.

``` ts
//wheres-my-toilet / src / hooks / home_page/useGetData.ts 
export default function useGetData() {
  const [locationInfoData, setLocationInfoData] = useState<Location[] | null>([]);

  async function getData() {
    const { data, error } = await supabase.from('toilet_location').select(' * ');

    setLocationInfoData(data);
    return { data, error };
  }

  useEffect(() => {
    getData();
  }, []);

  return { locationInfoData };
}
```

(2)  지오로케이션 api 를 통해 받아온  나의 현재 위치 데이터가 저장된  zustand 에서 데이터를 가져와서   지도에 표현을 해주었습니다. 

```ts
// zustand 파일
import { create } from 'zustand';

type Store = {
  userLocation: { lat: number; lng: number };
  setLocation: (val: { lat: number; lng: number }) => void;
};
export const useUserLocationStore = create<Store>()((set) => ({
  userLocation: { lat: 37.5560919, lng: 127.146551 }, //임시 기본값
  setLocation: (val) => set({ userLocation: { lat: val.lat, lng: val.lng } }),
}));

//  zustand에 저장되어 있는  사용자 위치데이터 가져오기
  const { userLocation } = useUserLocationStore();
```

|기능|스크린샷|

- 지오로케이션 api를 통해 받아온 나의 현재 위치 데이터가 저장된 zustand 에서 
데이터를 가져와서 지도에 표현한 것을 말합니다. 그리고  현재 나의 위치와  근접한
화장실도 나타내었습니다.
![image](https://github.com/wheres-my-toilet/wheres-my-toilet/assets/98266983/1c0be257-5f83-435e-a3ee-4f6348f9d3ba)

2024-03-21 08:15 UTC, ketchup0211 requested changes

2024-03-21 08:15 UTC, ketchup0211 commented on src/app/home_page/page.tsx
> +  function getDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
이 함수는 src 아래에 util 폴더를 만들어 따로 분리하면 더 좋을 것 같아요!

2024-03-21 08:15 UTC, ketchup0211 commented on src/app/home_page/page.tsx
> +  function getDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
입력 값 받을 때 4개를 받지 말고, 객체 형태로 받아 1개의 argument만 있도록 해주세요!

2024-03-21 08:15 UTC, ketchup0211 commented on src/app/home_page/page.tsx
> +      const distance = getDistance(
여기도 마찬가지로 객체로 전달해주세요!

2024-03-21 08:28 UTC, ketchup0211 commented
수고 많으셨습니다! 단테님 최고💪🏻

2024-03-21 08:37 UTC, jigico commented
기능 구현하느라 시간도 없으실텐데 헤더 컴포넌트 렌더링 이슈까지!! 
이렇게 하나 더 배워갑니다~~!! 👍👍

2024-03-21 11:14 UTC, Nobuki-Kato reviewed
제일 어렵다고 느껴지는 기능이였는데 해결해 나가시는게 너무 대단해요

2024-03-21 11:14 UTC, Nobuki-Kato commented on src/app/home_page/page.tsx
>  export default function HomePage() {
컨밴션이 지켜지지 않은 것 같아요..! rafce로 작성되지 않은 것 같아요

2024-03-22 02:03 UTC, Andante23 reviewed
Finish your review 변경

2024-03-22 02:03 UTC, Andante23 commented on src/app/home_page/page.tsx
>  export default function HomePage() {
일단은  저의 homePage 을 rafce 로 바꾸었습니다.!!!! 알려주셔서 감사합니다.
![image](https://github.com/wheres-my-toilet/wheres-my-toilet/assets/98266983/bb580a78-9bf5-4c16-9511-28c3b4f55178)

2024-03-22 02:03 UTC, Andante23 commented on src/app/home_page/page.tsx
> +  function getDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
util 에 제가 맡고 있는  페이지이름의 폴더하위에 다음과 같이  생성하였습니다.
![image](https://github.com/wheres-my-toilet/wheres-my-toilet/assets/98266983/e3ddf643-1c71-49e9-a21d-552e3ce4ed26)

2024-03-22 11:12 UTC, Andante23 reviewed
ttttt

2024-03-22 11:12 UTC, Andante23 commented on src/app/home_page/page.tsx
> +  function getDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
```
//  수정된 getDistance 유틸 함수입니다.
import { Distance } from '@/types/home_page/types';

export default function getDistance({ lat1, lon1, lat2, lon2 }: Distance): number {
  const R = 6371; // 지구의 반지름 (단위: km)
  const dLat = (lat2 - lat1) * (Math.PI / 180);
  const dLon = (lon2 - lon1) * (Math.PI / 180);
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * (Math.PI / 180)) * Math.cos(lat2 * (Math.PI / 180)) * Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  const distance = R * c; // 두 지점 사이의 거리 (단위: km)
  return distance;
}
```

2024-03-22 11:12 UTC, Andante23 commented on src/app/home_page/page.tsx
> +      const distance = getDistance(
수정된  findNearestLocation.ts 유틸함수입니다.
```
import { Location, UserLocation } from '@/types/home_page/types';
import getDistance from './getDistance';

export default function findNearestLocation({
  userLocation,
  data,
}: {
  userLocation: UserLocation;
  data: Location[] | null;
}): Location | null {
  let minDistance = Infinity;
  let nearestLocation = null;

  data?.forEach((location) => {
    const distance = getDistance({
      lat1: userLocation.lat,
      lon1: userLocation.lng,
      lat2: location.toilet_latitude,
      lon2: location.toilet_longitude,
    });

    if (distance < minDistance) {
      minDistance = distance;
      nearestLocation = location;
    }
  });

  return nearestLocation;
}

```

2024-03-22 11:27 UTC, Andante23 commented on src/app/home_page/page.tsx
> -interface Location {
types/페이지 이름 이렇게 폴더 구조를 만들고  Location을 분리하였습니다.

2024-03-22 11:47 UTC, ketchup0211 approved these changes
클린-코드 너무 좋습니당👍🏻👍🏻 수고하셨어요!

2024-03-22 11:47 UTC, merged