Feature/detail
wheres-my-toilet/wheres-my-toilet pull request #9
Opened 2024-03-20 08:52 UTC by tjdwns335

## 📌 관련 이슈

## Task TODOLIST
- [ ] user 받아오는 부분 주석 제거!
- [ ] supabase.d.ts review_info의 user_id table number type 에서 string type으로 변경 충돌해결
- [ ] login 상태가 아니면 detail 페이지로 들어올 수 없게 만들어야 돼요!
- [ ] style이 하나도 없어서 style 추가

## ✨ 개발 내용
1. toilet_id 에 따른 map (여기 페이지로 이동할때 toilet_id 를 날려줘야 돼요)
2. 청결도, 위치, 인구밀도에 따라 값 받아오기
3. 리뷰 수정 삭제 로직

2024-03-20 10:46 UTC, jigico commented on src/app/detail_page/[id]/page.tsx
> +      <h1>{toiletLocation?.toilet_name}</h1>
로고 부분이 h1 태그로 되어 있어서 h2 태그로 변경해주시면 좋을 것 같습니다!

2024-03-20 10:50 UTC, jigico commented on src/components/review/ReviewInfo.tsx
> +    if (result === 5) return `⭐⭐⭐⭐⭐`;
switch case 문으로 작성하는건 어떨까요?

2024-03-20 10:57 UTC, ketchup0211 requested changes

2024-03-20 10:57 UTC, ketchup0211 commented on src/components/review/ReviewForm.tsx
> +    // e.preventDefault();
로직 완료 후 주석 제거해주세요!

2024-03-20 10:57 UTC, ketchup0211 commented on src/app/detail_page/[id]/page.tsx
> +// 로그인 안하면 이 페이지 접근 못하게 막아야될듯 해요 user 가져오는 부분 계속 오류나서 그 부분 다 주석입니다.
로그인 기능 완성 후 머지한다음에 수정하면 될 것 같습니다 ! 일단 주석 유지 부탁드릴게요:)

2024-03-20 10:57 UTC, ketchup0211 commented on src/components/review/ReviewForm.tsx
> +  const [toiletPopRate, setToiletPopRate] = useState(0);
toilet Rate와 관련된 useState 로직을 합치면 좋을 것 같습니다!
`const [toiletRate, setToiletRate] = useState({cleanRate:0, ...})` 
이런식으로요!

2024-03-20 10:57 UTC, ketchup0211 commented on src/components/review/ReviewForm.tsx
> +      user_nickname: '', // display Name 어떻게 받아올까요....
저 로그인 로직 완료되면 함께 고민해보아요...ㅎㅎㅎ ㅠㅠㅠㅠㅠ

2024-03-20 10:57 UTC, ketchup0211 commented on src/components/review/ReviewForm.tsx
> +          <select
select-option 반복되는 로직은 따로 컴포넌트를 분리해 관리하면 더 깔끔할 것 같습니다!

2024-03-20 11:18 UTC, jigico commented
오 엄청 많이 작업하셨네요!!

2024-03-21 07:26 UTC, tjdwns335 commented on src/shared/supabase/types/supabase.d.ts
>            user_nickname: string | null;
user_id 타입 바꿨어요 충돌대비!!!

2024-03-21 07:26 UTC, tjdwns335 commented on src/app/detail_page/[id]/page.tsx
> +
클릭하면 들어오는 곳이라 한번만 보여주면돼서 query로 안뻈어요

2024-03-21 07:26 UTC, tjdwns335 commented on src/components/review/ReviewForm.tsx
> +
Mutation 조언 좀요 작동은하는데 새로고침해야 추가돼요.

2024-03-21 07:26 UTC, tjdwns335 commented on src/components/review/ReviewInfo.tsx
> +
여기있는 Mutation은 오류 걸려서 주석처리 해놨어요 피드백 매우 간절

2024-03-21 07:26 UTC, tjdwns335 commented on src/components/review/reviewFunction/queryFunction.ts
> +};
changeReview, deleteReview  함수 가지고 올 때 에러 사항이 생깁니다.

2024-03-21 07:35 UTC, tjdwns335 commented on src/components/review/ReviewInfo.tsx
> +                      }}
**수정을 누르면 전부 다 인풋 으로 변환**
![image](https://github.com/wheres-my-toilet/wheres-my-toilet/assets/151831149/9b4306f2-8fa8-4532-851b-d405d4f53f54)
![image](https://github.com/wheres-my-toilet/wheres-my-toilet/assets/151831149/8f361275-5937-4de5-a516-898c9c32be38)
**시간 조건 추가해서 바뀌는건 하나만 바뀌긴하는데 이것도 피드백 좀 부탁드립니다.**

2024-03-21 07:35 UTC, tjdwns335 commented on src/app/detail_page/[id]/page.tsx
> +                </div>
![image](https://github.com/wheres-my-toilet/wheres-my-toilet/assets/151831149/01261c34-5cd0-4f80-9189-e032232884aa)

**

- [ ] 테이블에 있는 값 전부 다 출력 값을 합치고 평균 값으로 치환 피드백 부탁드려요

**

2024-03-21 08:02 UTC, ketchup0211 commented on src/shared/supabase/types/supabase.d.ts
>            user_nickname: string | null;
좋습니다!

2024-03-21 08:11 UTC, ketchup0211 requested changes

2024-03-21 08:11 UTC, ketchup0211 commented on src/components/review/ReviewInfo.tsx
> +                      }}
데이터 연결 관리를 
1. 유저 아이디와 유저가 작성한 리뷰 아이디를 매칭해 놓으면 좋을 것 같아요.
2. 수정으로 toggle될 때 선택한 review_id를 비교하여 선택한 리뷰 아이디와 일치한 리뷰 아이디 부분만 토글되도록 해야할 것 같아요.

2024-03-21 08:11 UTC, ketchup0211 commented on src/components/review/reviewFunction/queryFunction.ts
> +};
error 를 가져오고나서 처리하는 로직 추가해주세요!

2024-03-22 08:26 UTC, tjdwns335 commented on src/components/review/ReviewForm.tsx
> +  const { data } = useQuery({
리뷰를 추가하는 로직이 있어 안정적이게 user 받는 부분 zustand로 받을 수 있게 고칠까 생각 중입니다.

2024-03-22 11:43 UTC, ketchup0211 approved these changes
따봉도치가 따봉!

2024-03-22 11:43 UTC, merged